"""merge early-released revs + their dev-only chains for the sprint release

The revisions c00000000001 shipped early in a patch, so on this release -> main line they
keep MAIN's parents and each previously-unreleased chain (tips b00000000002) lands as a
SIBLING of main's head c00000000001 - so prod RUNS the chains instead of skipping them.
This empty merge joins the chains BEFORE c00000000001's descendants (which are repointed
onto it), so anything a descendant depends on - e.g. a schema created inside a chain
- is guaranteed present before those descendants run. Dev keeps its own order
untouched. See docs/migration-patch-backmerge.md.

Revision ID: b990fb343824
Revises: c00000000001, b00000000002
Create Date: (generated by reconcile_sprint_migration.py)

"""

# revision identifiers, used by Alembic.
revision = "b990fb343824"
down_revision = ("c00000000001", "b00000000002")
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    pass
